### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by matus-cuper** [matus-cuper/SEBC#2]

**Comment by mfernest** [comment]
@mikeridley please evaluate the work for this lab.

**Comment by mikeridley** [comment]
Looks like the content from 1_prechecks.md and 1_preinstall.md both ended up in 1_preinstall.md.  No big deal.

Overall, work looks very thorough.  Verified and set additional recommended parameters that are in our documentation but were not specifically mentioned in the lab instructions.  Great job.

Local repo config looks correct as well.
