### ISSUE TITLE
Resources labs

### ISSUE THREAD

**Issue by matus-cuper** [matus-cuper/SEBC#3]

**Comment by mfernest** [comment]
`0_YarnCalcs.md` file is empty.
Incorrect graphic in `1_static_pools.png`

Did you infer any causes for the difference in process time between your slowest and fastest trial?

Although the mistakes here are obvious clerical errors, I have to mark this lab as Incomplete.

**Comment by matus-cuper** [comment]
`0_YarnCalcs.md` is named like `0_YarnCalcs.xlsx`.
The fastest trial used a lots of containers (both mappers and reducers) with the smallest size of container memory and the slowest one was opposite of the fastest.
And I forgot to add output of time command.
